/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface RiskAssessment {
  'rbd' : number,
  'insomnia' : number,
  'sleepApnea' : number,
}
export interface SensorData {
  'hr' : number,
  'movement' : number,
  'hrv' : number,
  'spo2' : number,
  'timestamp' : bigint,
}
export type SleepRecordingId = string;
export interface SleepSession {
  'id' : SleepSessionId,
  'sleepScore' : number,
  'user' : Principal,
  'durationMinutes' : number,
  'notes' : string,
  'startTimestamp' : Time,
  'sensorReadings' : Array<SensorData>,
  'riskAssessment' : [] | [RiskAssessment],
}
export type SleepSessionId = bigint;
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'consentToResearch' : boolean,
  'email' : string,
  'consentToTracking' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addRiskAssessment' : ActorMethod<
    [SleepSessionId, RiskAssessment],
    undefined
  >,
  'addSensorReading' : ActorMethod<[SleepSessionId, SensorData], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteMyData' : ActorMethod<[], undefined>,
  'finishSession' : ActorMethod<[bigint, SleepSession], SleepSessionId>,
  'getCallerSession' : ActorMethod<[SleepSessionId], [] | [SleepSession]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyRecordings' : ActorMethod<
    [Array<SleepRecordingId>],
    Array<ExternalBlob>
  >,
  'getMySessions' : ActorMethod<[], Array<SleepSession>>,
  'getRecording' : ActorMethod<[SleepRecordingId], [] | [ExternalBlob]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'startSession' : ActorMethod<[SleepSession], SleepSessionId>,
  'uploadRecording' : ActorMethod<[SleepRecordingId, ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];