/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const SleepSessionId = IDL.Nat;
export const RiskAssessment = IDL.Record({
  'rbd' : IDL.Float64,
  'insomnia' : IDL.Float64,
  'sleepApnea' : IDL.Float64,
});
export const SensorData = IDL.Record({
  'hr' : IDL.Float64,
  'movement' : IDL.Float64,
  'hrv' : IDL.Float64,
  'spo2' : IDL.Float64,
  'timestamp' : IDL.Int,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const SleepSession = IDL.Record({
  'id' : SleepSessionId,
  'sleepScore' : IDL.Float64,
  'user' : IDL.Principal,
  'durationMinutes' : IDL.Float64,
  'notes' : IDL.Text,
  'startTimestamp' : Time,
  'sensorReadings' : IDL.Vec(SensorData),
  'riskAssessment' : IDL.Opt(RiskAssessment),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'consentToResearch' : IDL.Bool,
  'email' : IDL.Text,
  'consentToTracking' : IDL.Bool,
});
export const SleepRecordingId = IDL.Text;
export const ExternalBlob = IDL.Vec(IDL.Nat8);

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addRiskAssessment' : IDL.Func([SleepSessionId, RiskAssessment], [], []),
  'addSensorReading' : IDL.Func([SleepSessionId, SensorData], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteMyData' : IDL.Func([], [], []),
  'finishSession' : IDL.Func([IDL.Nat, SleepSession], [SleepSessionId], []),
  'getCallerSession' : IDL.Func(
      [SleepSessionId],
      [IDL.Opt(SleepSession)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyRecordings' : IDL.Func(
      [IDL.Vec(SleepRecordingId)],
      [IDL.Vec(ExternalBlob)],
      [],
    ),
  'getMySessions' : IDL.Func([], [IDL.Vec(SleepSession)], ['query']),
  'getRecording' : IDL.Func(
      [SleepRecordingId],
      [IDL.Opt(ExternalBlob)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'startSession' : IDL.Func([SleepSession], [SleepSessionId], []),
  'uploadRecording' : IDL.Func([SleepRecordingId, ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const SleepSessionId = IDL.Nat;
  const RiskAssessment = IDL.Record({
    'rbd' : IDL.Float64,
    'insomnia' : IDL.Float64,
    'sleepApnea' : IDL.Float64,
  });
  const SensorData = IDL.Record({
    'hr' : IDL.Float64,
    'movement' : IDL.Float64,
    'hrv' : IDL.Float64,
    'spo2' : IDL.Float64,
    'timestamp' : IDL.Int,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const SleepSession = IDL.Record({
    'id' : SleepSessionId,
    'sleepScore' : IDL.Float64,
    'user' : IDL.Principal,
    'durationMinutes' : IDL.Float64,
    'notes' : IDL.Text,
    'startTimestamp' : Time,
    'sensorReadings' : IDL.Vec(SensorData),
    'riskAssessment' : IDL.Opt(RiskAssessment),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'consentToResearch' : IDL.Bool,
    'email' : IDL.Text,
    'consentToTracking' : IDL.Bool,
  });
  const SleepRecordingId = IDL.Text;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addRiskAssessment' : IDL.Func([SleepSessionId, RiskAssessment], [], []),
    'addSensorReading' : IDL.Func([SleepSessionId, SensorData], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteMyData' : IDL.Func([], [], []),
    'finishSession' : IDL.Func([IDL.Nat, SleepSession], [SleepSessionId], []),
    'getCallerSession' : IDL.Func(
        [SleepSessionId],
        [IDL.Opt(SleepSession)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyRecordings' : IDL.Func(
        [IDL.Vec(SleepRecordingId)],
        [IDL.Vec(ExternalBlob)],
        [],
      ),
    'getMySessions' : IDL.Func([], [IDL.Vec(SleepSession)], ['query']),
    'getRecording' : IDL.Func(
        [SleepRecordingId],
        [IDL.Opt(ExternalBlob)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'startSession' : IDL.Func([SleepSession], [SleepSessionId], []),
    'uploadRecording' : IDL.Func([SleepRecordingId, ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };